import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Guard: registry <-> components-kb parity on type set and per-type version
 * (docs/RECONCILIATION.md's "Guard tests to add", item 6).
 *
 * `registry-0.45.1.json` (generated by executing the framework — jsdom + real
 * `settingsFormMarkup` + full migrator replay) and `components-kb/_index.json`
 * (regex-parsed from renderer source) are two independently-generated
 * ground-truth sources for "does this component type exist, at what
 * version". Nothing compared them, which is exactly how `dataContext`
 * (registry: null, kb: 8) and `permissionTagGroup` (registry: 2, kb: null)
 * drifted apart between two generations 8 days apart, silently.
 *
 * This test does NOT try to make the two sources agree — RECONCILIATION.md
 * is explicit that `registry-0.45.1.json` is sole authority on prop/version
 * facts and the KB is not to be hand-edited to match it (nor vice versa;
 * both are generated artifacts, never edited by hand — see the plugin's own
 * `assets/registry/**`/`assets/components-kb/**` generation scripts). So it
 * pins the CURRENT, known divergence exactly (type-set and version), and
 * fails on anything beyond it — a NEW divergence is a new silent-drift
 * incident exactly like the one that motivated this test, and must not pass
 * quietly.
 *
 * If one of these fixed-point pins ever converges (e.g. a future regen
 * gives `dataContext` a real version in the registry), this test will fail
 * with a clear message — that's the signal to shrink the pinned set, not to
 * touch either generated file.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const FORM_EDIT_DIR = join(HERE, '..', 'skills', 'shesha-form-edit');
const REGISTRY_PATH = join(FORM_EDIT_DIR, 'assets', 'registry', 'registry-0.45.1.json');
const KB_INDEX_PATH = join(FORM_EDIT_DIR, 'assets', 'components-kb', '_index.json');

const registry = JSON.parse(readFileSync(REGISTRY_PATH, 'utf8')).components;
const kb = JSON.parse(readFileSync(KB_INDEX_PATH, 'utf8'));

const registryTypes = new Set(Object.keys(registry));
const kbTypes = new Set(Object.keys(kb).filter((k) => !k.startsWith('_')));

/**
 * Known, current type-set divergence (measured when this test was written).
 * `datatable_template` and `headerAppControl` exist in the registry but not
 * the KB; `threeStateSwitch` exists in the KB but not the registry.
 */
const KNOWN_ONLY_IN_REGISTRY = new Set(['datatable_template', 'headerAppControl']);
const KNOWN_ONLY_IN_KB = new Set(['threeStateSwitch']);

/**
 * Known, current per-type version divergence for types present in both
 * sources — the exact pair RECONCILIATION.md names as the incident that
 * motivated this guard test.
 */
const KNOWN_VERSION_DIVERGENCE = {
  dataContext: { registry: null, kb: 8 },
  permissionTagGroup: { registry: 2, kb: null },
};

test('registry/KB type-set divergence is exactly the known, pinned set (no new drift)', () => {
  const onlyInRegistry = [...registryTypes].filter((t) => !kbTypes.has(t)).sort();
  const onlyInKb = [...kbTypes].filter((t) => !registryTypes.has(t)).sort();

  const unexpectedOnlyInRegistry = onlyInRegistry.filter((t) => !KNOWN_ONLY_IN_REGISTRY.has(t));
  const unexpectedOnlyInKb = onlyInKb.filter((t) => !KNOWN_ONLY_IN_KB.has(t));
  assert.deepEqual(
    unexpectedOnlyInRegistry, [],
    `new type(s) only in registry-0.45.1.json, not in components-kb/_index.json (beyond the `
    + `pinned ${JSON.stringify([...KNOWN_ONLY_IN_REGISTRY])}): ${unexpectedOnlyInRegistry.join(', ')}`,
  );
  assert.deepEqual(
    unexpectedOnlyInKb, [],
    `new type(s) only in components-kb/_index.json, not in registry-0.45.1.json (beyond the `
    + `pinned ${JSON.stringify([...KNOWN_ONLY_IN_KB])}): ${unexpectedOnlyInKb.join(', ')}`,
  );

  // Guard the pins themselves: if a known divergence disappears (the type
  // now exists on both sides), shrink the pinned set instead of leaving a
  // stale allowance.
  const stillOnlyInRegistry = new Set(onlyInRegistry);
  const stillOnlyInKb = new Set(onlyInKb);
  for (const t of KNOWN_ONLY_IN_REGISTRY) {
    assert.ok(stillOnlyInRegistry.has(t), `"${t}" is no longer registry-only — remove it from KNOWN_ONLY_IN_REGISTRY`);
  }
  for (const t of KNOWN_ONLY_IN_KB) {
    assert.ok(stillOnlyInKb.has(t), `"${t}" is no longer KB-only — remove it from KNOWN_ONLY_IN_KB`);
  }
});

test('registry/KB per-type version divergence is exactly the known, pinned pair (no new drift)', () => {
  const mismatches = [];
  for (const t of registryTypes) {
    if (!kbTypes.has(t)) continue;
    const rv = registry[t].version;
    const kv = kb[t].version;
    if (rv !== kv) mismatches.push({ type: t, registry: rv, kb: kv });
  }

  const unexpected = mismatches.filter((m) => {
    const known = KNOWN_VERSION_DIVERGENCE[m.type];
    return !(known && known.registry === m.registry && known.kb === m.kb);
  });
  assert.deepEqual(
    unexpected, [],
    `new registry/KB version mismatch(es) beyond the pinned ${JSON.stringify(KNOWN_VERSION_DIVERGENCE)}: `
    + `${JSON.stringify(unexpected)} — a form authored against one source and validated `
    + 'against the other can silently ship a stale/wrong version',
  );

  // Guard the pins themselves.
  for (const [type, known] of Object.entries(KNOWN_VERSION_DIVERGENCE)) {
    const found = mismatches.find((m) => m.type === type);
    assert.ok(
      found,
      `"${type}" no longer diverges between registry (${known.registry}) and KB (${known.kb}) `
      + `— remove it from KNOWN_VERSION_DIVERGENCE`,
    );
  }
});
