# ============================================================================
# Shesha Project - Entity CRUD Endpoint Test Script (PowerShell)
# ============================================================================
# Works with any Shesha-based project. Entity list is auto-generated by
# Run-EndpointTests.ps1 -UpdateEntities based on [Entity] attributes.
# Usage: .\Test-Endpoints.ps1 [-BaseUrl "http://localhost:21021"] [-Username "admin"] [-Password "123qwe"] [-FullErrors]
# ============================================================================

param(
    [string]$BaseUrl = "http://localhost:21021",
    [string]$Username = "admin",
    [string]$Password = "123qwe",
    [switch]$FullErrors
)

# Error truncation limit (0 = no truncation when FullErrors is set)
$ErrorTruncateLength = if ($FullErrors) { 0 } else { 200 }

function Get-TruncatedError {
    param([string]$ErrorText, [int]$MaxLength)
    if ($MaxLength -eq 0 -or -not $ErrorText) {
        return $ErrorText
    }
    if ($ErrorText.Length -gt $MaxLength) {
        return $ErrorText.Substring(0, $MaxLength) + "..."
    }
    return $ErrorText
}

# All domain entities to test
# NOTE: This list is auto-populated by Run-EndpointTests.ps1 -UpdateEntities
# which scans the Domain folder for entity classes with [Entity] attribute.
# Run with -UpdateEntities flag to scan the Domain folder and update this list
$Entities = @(
    @{ Type = "PLACEHOLDER"; Name = "PLACEHOLDER" }
)

if ($Entities.Count -eq 0 -or ($Entities.Count -eq 1 -and $Entities[0].Type -eq "PLACEHOLDER")) {
    Write-Host ""
    Write-Host "WARNING: No entities configured. Run with -UpdateEntities to scan the domain folder." -ForegroundColor Yellow
    Write-Host ""
    exit 0
}

$Results = @()
$ErrorList = @()
$Passed = 0
$Failed = 0

Write-Host ""
Write-Host "============================================================================" -ForegroundColor Cyan
Write-Host "  Shesha Project - Entity CRUD Endpoint Test" -ForegroundColor Cyan
Write-Host "============================================================================" -ForegroundColor Cyan
Write-Host "  Server: $BaseUrl"
Write-Host "  User:   $Username"
Write-Host "  Time:   $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Host "============================================================================" -ForegroundColor Cyan
Write-Host ""

# Step 1: Authenticate
Write-Host "Authenticating..." -ForegroundColor Yellow
try {
    $AuthBody = @{
        userNameOrEmailAddress = $Username
        password = $Password
    } | ConvertTo-Json

    $AuthResponse = Invoke-RestMethod -Uri "$BaseUrl/api/TokenAuth/Authenticate" `
        -Method Post `
        -ContentType "application/json" `
        -Body $AuthBody `
        -ErrorAction Stop

    if (-not $AuthResponse.success) {
        Write-Host "ERROR: Authentication failed - $($AuthResponse.error.message)" -ForegroundColor Red
        exit 1
    }

    $Token = $AuthResponse.result.accessToken
    Write-Host "Authentication successful" -ForegroundColor Green
}
catch {
    Write-Host "ERROR: Authentication failed - $_" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Testing endpoints..." -ForegroundColor Yellow
Write-Host ""

# Step 2: Test each entity
$Headers = @{
    "Authorization" = "Bearer $Token"
}

foreach ($Entity in $Entities) {
    $EntityType = $Entity.Type
    $EntityName = $Entity.Name
    $Uri = "$BaseUrl/api/services/app/Entities/GetAll?entityType=$EntityType&maxResultCount=1"

    try {
        $WebResponse = Invoke-WebRequest -Uri $Uri -Headers $Headers -Method Get -UseBasicParsing -ErrorAction Stop
        $Response = $WebResponse.Content | ConvertFrom-Json

        if ($Response.success) {
            $TotalCount = $Response.result.totalCount
            $Results += [PSCustomObject]@{
                Name = $EntityName
                Status = "PASS"
                Details = "$TotalCount records"
                ErrorType = $null
            }
            $Passed++
        }
        else {
            $ErrorDetails = $Response.error.details
            $ErrorType = switch -Regex ($ErrorDetails) {
                "field with the name.*already registered" { "GraphQL Field Conflict" }
                "Invalid column name" { "Missing DB Column" }
                "Entity with class name.*not found" { "Entity Not Found" }
                "did not login" { "Auth Required" }
                default { "API Error" }
            }

            $Results += [PSCustomObject]@{
                Name = $EntityName
                Status = "FAIL"
                Details = $ErrorType
                ErrorType = $ErrorType
            }
            $ErrorList += [PSCustomObject]@{
                Name = $EntityName
                Type = $ErrorType
                Details = Get-TruncatedError -ErrorText $ErrorDetails -MaxLength $ErrorTruncateLength
                FullDetails = $ErrorDetails
            }
            $Failed++
        }
    }
    catch {
        $ErrorDetails = $_.Exception.Message
        $ErrorType = "Request Error"

        # Try to parse error response from exception
        if ($_.ErrorDetails.Message) {
            try {
                $ErrorJson = $_.ErrorDetails.Message | ConvertFrom-Json
                if ($ErrorJson.error.details) {
                    $ErrorDetails = $ErrorJson.error.details
                    $ErrorType = switch -Regex ($ErrorDetails) {
                        "field with the name.*already registered" { "GraphQL Field Conflict" }
                        "Invalid column name" { "Missing DB Column" }
                        "Entity with class name.*not found" { "Entity Not Found" }
                        "did not login" { "Auth Required" }
                        default { "API Error" }
                    }
                }
            }
            catch { }
        }

        $Results += [PSCustomObject]@{
            Name = $EntityName
            Status = "FAIL"
            Details = $ErrorType
            ErrorType = $ErrorType
        }
        $ErrorList += [PSCustomObject]@{
            Name = $EntityName
            Type = $ErrorType
            Details = Get-TruncatedError -ErrorText $ErrorDetails -MaxLength $ErrorTruncateLength
            FullDetails = $ErrorDetails
        }
        $Failed++
    }
}

# Step 3: Test Swagger
Write-Host "Testing Swagger endpoint..." -ForegroundColor Yellow
try {
    $SwaggerResponse = Invoke-WebRequest -Uri "$BaseUrl/swagger/v1/swagger.json" -Method Get -ErrorAction Stop
    $SwaggerResult = "PASS"
}
catch {
    $SwaggerResult = "FAIL (HTTP $($_.Exception.Response.StatusCode.value__))"
}

# Step 4: Print Results
Write-Host ""
Write-Host "============================================================================" -ForegroundColor Cyan
Write-Host "  TEST RESULTS SUMMARY" -ForegroundColor Cyan
Write-Host "============================================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host ("{0,-30} {1,-12} {2}" -f "ENTITY", "STATUS", "DETAILS")
Write-Host ("{0,-30} {1,-12} {2}" -f "------", "------", "-------")

foreach ($Result in $Results) {
    $StatusColor = if ($Result.Status -eq "PASS") { "Green" } else { "Red" }
    Write-Host ("{0,-30} " -f $Result.Name) -NoNewline
    Write-Host ("{0,-12} " -f $Result.Status) -ForegroundColor $StatusColor -NoNewline
    Write-Host $Result.Details
}

Write-Host ""
$SwaggerColor = if ($SwaggerResult -eq "PASS") { "Green" } else { "Red" }
Write-Host ("{0,-30} " -f "Swagger UI") -NoNewline
Write-Host $SwaggerResult -ForegroundColor $SwaggerColor

Write-Host ""
Write-Host "============================================================================" -ForegroundColor Cyan
Write-Host -NoNewline "  SUMMARY: "
Write-Host -NoNewline "$Passed passed" -ForegroundColor Green
Write-Host -NoNewline ", "
Write-Host -NoNewline "$Failed failed" -ForegroundColor Red
Write-Host " out of $($Entities.Count) entities"
Write-Host "============================================================================" -ForegroundColor Cyan

# Step 5: Print Error Details if any failures
if ($Failed -gt 0) {
    Write-Host ""
    Write-Host "============================================================================" -ForegroundColor Cyan
    Write-Host "  ERROR DETAILS" -ForegroundColor Cyan
    Write-Host "============================================================================" -ForegroundColor Cyan

    # Group errors by type
    $ErrorGroups = $ErrorList | Group-Object -Property Type

    Write-Host ""
    foreach ($Group in $ErrorGroups) {
        Write-Host "$($Group.Name):" -ForegroundColor Yellow
        Write-Host "  Affected: $($Group.Group.Name -join ', ')"
        Write-Host ""
    }

    Write-Host "----------------------------------------------------------------------------"
    if ($FullErrors) {
        Write-Host "Detailed Errors (full output):"
    } else {
        Write-Host "Detailed Errors (first 200 chars, use -FullErrors for complete output):"
    }
    Write-Host "----------------------------------------------------------------------------"
    foreach ($Err in $ErrorList) {
        Write-Host ""
        Write-Host "$($Err.Name):" -ForegroundColor Yellow
        $ErrorOutput = if ($FullErrors -and $Err.FullDetails) { $Err.FullDetails } else { $Err.Details }
        Write-Host "  $ErrorOutput"
    }
}

Write-Host ""
Write-Host "============================================================================" -ForegroundColor Cyan
Write-Host "  Test completed at $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Host "============================================================================" -ForegroundColor Cyan
Write-Host ""

# Return exit code based on results
exit $Failed
