// The error catalogue is generated and covers every code the compiler can throw
// (§2.7, INV-2). Two assertions: it is byte-identical to a fresh generation (no
// hand-edit drift), and every error code raised anywhere in src is present — so a
// code added without a catalogue row fails a test rather than shipping undocumented.

import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { scan } from '../tools/gen-catalogue.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..', '..', '..');
const SRC = path.join(ROOT, 'packages/sfs/src');

test('error-catalogue.json is byte-identical to a fresh generation', () => {
  const committed = fs.readFileSync(path.join(ROOT, 'packages/sfs/config/error-catalogue.json'), 'utf8');
  const fresh = `${JSON.stringify({
    _provenance: 'GENERATED by packages/sfs/tools/gen-catalogue.mjs from every new <X>Error(code, message) in packages/sfs/src. Do not hand-edit; run the generator. §2.7.',
    count: scan().length,
    rows: scan(),
  }, null, 2)}\n`;
  assert.equal(committed, fresh, 'error-catalogue.json is stale — run node packages/sfs/tools/gen-catalogue.mjs');
});

test('every error code raised in src appears in the catalogue', () => {
  const catalogue = new Set(JSON.parse(fs.readFileSync(path.join(ROOT, 'packages/sfs/config/error-catalogue.json'), 'utf8'))
    .rows.map((/** @type {{code:string}} */ r) => r.code));
  /** @type {Set<string>} */
  const raised = new Set();
  /** @param {string} dir @returns {void} */
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const abs = path.join(dir, entry.name);
      if (entry.isDirectory()) { walk(abs); continue; }
      if (!entry.name.endsWith('.mjs')) continue;
      const text = fs.readFileSync(abs, 'utf8');
      for (const m of text.matchAll(/new\s+\w*Error\(\s*'([A-Z]{2,4}-\d{3,4})'/g)) raised.add(m[1]);
    }
  };
  walk(SRC);
  assert.ok(raised.size > 0, 'no error codes found in src — the scan is vacuous');
  const missing = [...raised].filter((c) => !catalogue.has(c)).sort();
  assert.deepEqual(missing, [], `codes raised in src but absent from the catalogue: ${missing.join(', ')}`);
});
